export default {
  // these are the just examples
  helvetica: {
    bold: "helvetica-Bold",
    boldItalic: "helvetica-BoldItalic",
    boldLegacy: "helvetica-BoldLegacy",
    boldLegacyItalic: "helvetica-BoldLegacyItalic",
    italic: "helvetica-Italic",
    italicLegacy: "helvetica-LegacyItalic",
    light: "helvetica-Light",
    lightItalic: "helvetica-LightItalic",
    lightLegacy: "helvetica-LightLegacy",
    lightLegacyItalic: "helvetica-LightLegacyItalic",
    medium: "helvetica-Medium",
    mediumItalic: "helvetica-MediumItalic",
    mediumLegacy: "helvetica-MediumLegacy",
    mediumLegacyItalic: "helvetica-MediumLegacyItalic",
    regular: "helvetica-Regular",
    regularLegacy: "helvetica-RegularLegacy",
    semiBold: "helvetica-SemiBold",
    semiBoldItalic: "helvetica-SemiBoldItalic",
    semiBoldLegacy: "helvetica-SemiBoldLegacy",
    semiBoldLegacyItalic: "helvetica-SemiBoldLegacyItalic",
  },
  grotesk: "Grotesk",
};
