export default {
  montserrat: {
    black: "Montserrat-Black",
    blackItalic: "Montserrat-BlackItalic",
    bold: "Montserrat-Bold",
    boldItalic: "Montserrat-BoldItalic",
    extraBold: "Montserrat-ExtraBold",
    extraBoldItalic: "Montserrat-ExtraBoldItalic",
    extraLight: "Montserrat-ExtraLight",
    extraLightItalic: "Montserrat-ExtraLightItalic",
    italic: "Montserrat-Italic",
    light: "Montserrat-Light",
    lightItalic: "Montserrat-LightItalic",
    medium: "Montserrat-Medium",
    mediumItalic: "Montserrat-MediumItalic",
    regular: "Montserrat-Regular",
    semiBold: "Montserrat-SemiBold",
    semiBoldItalic: "Montserrat-SemiBoldItalic",
    thin: "Montserrat-Thin",
    thinItalic: "Montserrat-ThinItalic",
  },
};
